add_newline = true

format = """
[┌─](bold green) $directory$rust$package$git_branch$git_status
[└─>](bold green) """

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
disabled = false
show_always = true

[git_branch]
style = "green"
